// PHASE 2 — Library curation (network-free). Reads matched.json, applies an inclusion
// floor, deduplicates remakes/alt-cuts, re-tiers by a blended popularity+acclaim score,
// and emits data/movies.js. Operates only on films that already have frames downloaded.
//
//   node curate.js            # rebuild data/movies.js
//   node curate.js --dry      # print what would change, write nothing
//
// Decoys are randomized at runtime in index.html, so this emits decoys: [] (legacy field).
const fs = require('fs');
const path = require('path');
const C = require('./config');
const T = require('./lib/text');

const FLOOR_VOTES = 200;          // inclusion floor: drop films below this many TMDb votes
const W_VOTES = 0.6, W_RATING = 0.4;   // blend weights for re-tiering
const KEEP_OVERRIDE = new Set(['funny-games-2']); // prefer 1997 original over 2008 remake
const DROP_OVERRIDE = new Set(['funny-games']);

const norm = (t) => T.norm(t);

function tierFor(p) {
  for (const t of C.tiers) if (p >= t.min) return t.key;
  return 'cinephile';
}

function run({ dry = false } = {}) {
  const all = JSON.parse(fs.readFileSync(C.paths.matched, 'utf8'));
  let films = all.filter((m) => (m.frames || []).length >= C.frames.min);
  const start = films.length;

  // 1. inclusion floor — drop obscure tail and broken metadata
  const belowFloor = [];
  films = films.filter((f) => {
    const keep = f.vote_count >= FLOOR_VOTES && f.vote_average > 0;
    if (!keep) belowFloor.push(f);
    return keep;
  });

  // 2. deduplicate by normalized title — keep the version most people have seen
  //    (highest vote_count), with manual overrides for remake/original edge cases.
  const groups = new Map();
  for (const f of films) {
    const k = norm(f.title);
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k).push(f);
  }
  const dropped = [];
  films = [];
  for (const [, group] of groups) {
    if (group.length === 1) { films.push(group[0]); continue; }
    let keep = group.find((f) => KEEP_OVERRIDE.has(f.slug));
    if (!keep) keep = group.filter((f) => !DROP_OVERRIDE.has(f.slug))
      .sort((a, b) => b.vote_count - a.vote_count)[0] || group[0];
    for (const f of group) if (f !== keep) dropped.push(f);
    films.push(keep);
  }

  // 3. re-tier by blended z(log vote_count) + z(vote_average)
  const logv = films.map((f) => Math.log(f.vote_count));
  const rat = films.map((f) => f.vote_average);
  const stats = (arr) => {
    const mean = arr.reduce((s, x) => s + x, 0) / arr.length;
    const sd = Math.sqrt(arr.reduce((s, x) => s + (x - mean) ** 2, 0) / arr.length) || 1;
    return { mean, sd };
  };
  const sv = stats(logv), sr = stats(rat);
  films.forEach((f) => {
    const zv = (Math.log(f.vote_count) - sv.mean) / sv.sd;
    const zr = (f.vote_average - sr.mean) / sr.sd;
    f._score = W_VOTES * zv + W_RATING * zr;
  });
  const sorted = [...films].sort((a, b) => a._score - b._score); // ascending: low score = hardest
  const n = sorted.length;
  sorted.forEach((f, i) => { f.difficulty = tierFor(n <= 1 ? 1 : i / (n - 1)); });

  // emit (stable order: tier then title)
  const tierOrder = { easy: 0, medium: 1, hard: 2, veryhard: 3, cinephile: 4 };
  const out = sorted
    .map((f) => ({
      title: f.title, year: f.year, director: f.director, tmdbId: f.tmdbId,
      country: f.country, difficulty: f.difficulty, decoys: [], frames: f.frames,
    }))
    .sort((a, b) => (tierOrder[a.difficulty] - tierOrder[b.difficulty]) || a.title.localeCompare(b.title));

  const counts = out.reduce((m, f) => ((m[f.difficulty] = (m[f.difficulty] || 0) + 1), m), {});

  console.log(`Started with ${start} films (>=${C.frames.min} frames)`);
  console.log(`  − ${belowFloor.length} below floor (vote_count<${FLOOR_VOTES} or no rating)`);
  console.log(`  − ${dropped.length} duplicate/remake versions`);
  console.log(`  = ${out.length} films  ${JSON.stringify(counts)}`);
  if (dropped.length) {
    console.log('\nDeduped (dropped → kept):');
    for (const f of dropped) {
      const kept = films.find((k) => norm(k.title) === norm(f.title));
      console.log(`  ${f.title} (${f.year}) vc=${f.vote_count}  →  kept ${kept.year} vc=${kept.vote_count}`);
    }
  }

  if (dry) { console.log('\n--dry: no file written.'); return out; }

  const banner = `// AUTO-GENERATED by tools/curate.js — do not edit by hand.\n` +
    `// ${out.length} films · ${JSON.stringify(counts)}\n`;
  const body = `const MOVIES = ${JSON.stringify(out, null, 2)};\n` +
    `if (typeof module !== "undefined") module.exports = MOVIES;\n`;
  fs.mkdirSync(path.dirname(C.paths.manifest), { recursive: true });
  fs.writeFileSync(C.paths.manifest, banner + body);
  console.log(`\nWrote → ${path.relative(C.paths.root, C.paths.manifest)}`);
  console.log('Remember to bump ?v= in index.html.');
  return out;
}

if (require.main === module) run({ dry: process.argv.includes('--dry') });
module.exports = { run };
